name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Backend Tests
        run: |
          pytest backend/tests/

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Backend (FastAPI)
        run: |
          ssh ubuntu@your-server-ip 'cd /var/www/tender-backend && git pull && docker-compose up --build -d'

      - name: Deploy Frontend (React)
        run: |
          ssh ubuntu@your-server-ip 'cd /var/www/tender-frontend && git pull && npm install && npm run build'
